import Head from 'next/head'
import Image from 'next/image'
import Navbar from './component/navbar'
import Slider from './component/slider'
import { useAmp } from 'next/amp'
import Offer from './component/offer'
import TransNavbar from './component/transparentNav'
import Services from './component/services'
import Choose from './component/choose'
import Commitment from './component/commitment'




export const config = { amp: 'hybrid' }

export default function Home() {
  const isAmp = useAmp()

  return (
     <>
     {
       isAmp ? 'amp' : <div>
       <Head>
         <title>ConvertPool</title>
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />
       </Head>
       <Navbar></Navbar>
        
         <div className='nav-banner'>
         <TransNavbar></TransNavbar>
           <Slider></Slider>
         </div>
         <Offer></Offer>
         <Services></Services>
         <Choose></Choose>
         <Commitment></Commitment>
        
     </div>
     }
     </>
  )
}
